package com.selsa.credito.condicion_credito;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CLIENTE_INFO_LABORAL implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CLIENTE_INFO_LABORAL_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CLIENTE_INFO_LABORAL_ID_GENERATOR", sequenceName = "CLIENTE_INFO_LABORAL_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String NOMBRE_EMPRESA_CLIENTE;

	private java.lang.String CODIGO_TIPO_CONTRATO_CLIENTE;

	private java.lang.String TIPO_CONTRATO_CLIENTE;

	private java.util.Date FECHA_INGRESO_EMPRESA;

	private java.util.Date FECHA_VENCE_CONTRATO_TERMINO_FIJO;

	private java.lang.String SALARIO_INTEGRAL_CLIENTE;

	private java.lang.String CARGO_ACTUAL_CLIENTE;

	private java.lang.String JORNADA_LABORAL_CLIENTE;

	private java.lang.String CODIGO_DEPENDENCIA_ACTUAL_CLIENTE;

	private java.lang.String CODIGO_CARGO_ACTUAL_CLIENTE;

	public CLIENTE_INFO_LABORAL() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getNOMBRE_EMPRESA_CLIENTE() {
		return this.NOMBRE_EMPRESA_CLIENTE;
	}

	public void setNOMBRE_EMPRESA_CLIENTE(
			java.lang.String NOMBRE_EMPRESA_CLIENTE) {
		this.NOMBRE_EMPRESA_CLIENTE = NOMBRE_EMPRESA_CLIENTE;
	}

	public java.lang.String getCODIGO_TIPO_CONTRATO_CLIENTE() {
		return this.CODIGO_TIPO_CONTRATO_CLIENTE;
	}

	public void setCODIGO_TIPO_CONTRATO_CLIENTE(
			java.lang.String CODIGO_TIPO_CONTRATO_CLIENTE) {
		this.CODIGO_TIPO_CONTRATO_CLIENTE = CODIGO_TIPO_CONTRATO_CLIENTE;
	}

	public java.lang.String getTIPO_CONTRATO_CLIENTE() {
		return this.TIPO_CONTRATO_CLIENTE;
	}

	public void setTIPO_CONTRATO_CLIENTE(java.lang.String TIPO_CONTRATO_CLIENTE) {
		this.TIPO_CONTRATO_CLIENTE = TIPO_CONTRATO_CLIENTE;
	}

	public java.util.Date getFECHA_INGRESO_EMPRESA() {
		return this.FECHA_INGRESO_EMPRESA;
	}

	public void setFECHA_INGRESO_EMPRESA(java.util.Date FECHA_INGRESO_EMPRESA) {
		this.FECHA_INGRESO_EMPRESA = FECHA_INGRESO_EMPRESA;
	}

	public java.util.Date getFECHA_VENCE_CONTRATO_TERMINO_FIJO() {
		return this.FECHA_VENCE_CONTRATO_TERMINO_FIJO;
	}

	public void setFECHA_VENCE_CONTRATO_TERMINO_FIJO(
			java.util.Date FECHA_VENCE_CONTRATO_TERMINO_FIJO) {
		this.FECHA_VENCE_CONTRATO_TERMINO_FIJO = FECHA_VENCE_CONTRATO_TERMINO_FIJO;
	}

	public java.lang.String getSALARIO_INTEGRAL_CLIENTE() {
		return this.SALARIO_INTEGRAL_CLIENTE;
	}

	public void setSALARIO_INTEGRAL_CLIENTE(
			java.lang.String SALARIO_INTEGRAL_CLIENTE) {
		this.SALARIO_INTEGRAL_CLIENTE = SALARIO_INTEGRAL_CLIENTE;
	}

	public java.lang.String getCARGO_ACTUAL_CLIENTE() {
		return this.CARGO_ACTUAL_CLIENTE;
	}

	public void setCARGO_ACTUAL_CLIENTE(java.lang.String CARGO_ACTUAL_CLIENTE) {
		this.CARGO_ACTUAL_CLIENTE = CARGO_ACTUAL_CLIENTE;
	}

	public java.lang.String getJORNADA_LABORAL_CLIENTE() {
		return this.JORNADA_LABORAL_CLIENTE;
	}

	public void setJORNADA_LABORAL_CLIENTE(
			java.lang.String JORNADA_LABORAL_CLIENTE) {
		this.JORNADA_LABORAL_CLIENTE = JORNADA_LABORAL_CLIENTE;
	}

	public java.lang.String getCODIGO_DEPENDENCIA_ACTUAL_CLIENTE() {
		return this.CODIGO_DEPENDENCIA_ACTUAL_CLIENTE;
	}

	public void setCODIGO_DEPENDENCIA_ACTUAL_CLIENTE(
			java.lang.String CODIGO_DEPENDENCIA_ACTUAL_CLIENTE) {
		this.CODIGO_DEPENDENCIA_ACTUAL_CLIENTE = CODIGO_DEPENDENCIA_ACTUAL_CLIENTE;
	}

	public java.lang.String getCODIGO_CARGO_ACTUAL_CLIENTE() {
		return this.CODIGO_CARGO_ACTUAL_CLIENTE;
	}

	public void setCODIGO_CARGO_ACTUAL_CLIENTE(
			java.lang.String CODIGO_CARGO_ACTUAL_CLIENTE) {
		this.CODIGO_CARGO_ACTUAL_CLIENTE = CODIGO_CARGO_ACTUAL_CLIENTE;
	}

	public CLIENTE_INFO_LABORAL(java.lang.Long id,
			java.lang.String NOMBRE_EMPRESA_CLIENTE,
			java.lang.String CODIGO_TIPO_CONTRATO_CLIENTE,
			java.lang.String TIPO_CONTRATO_CLIENTE,
			java.util.Date FECHA_INGRESO_EMPRESA,
			java.util.Date FECHA_VENCE_CONTRATO_TERMINO_FIJO,
			java.lang.String SALARIO_INTEGRAL_CLIENTE,
			java.lang.String CARGO_ACTUAL_CLIENTE,
			java.lang.String JORNADA_LABORAL_CLIENTE,
			java.lang.String CODIGO_DEPENDENCIA_ACTUAL_CLIENTE,
			java.lang.String CODIGO_CARGO_ACTUAL_CLIENTE) {
		this.id = id;
		this.NOMBRE_EMPRESA_CLIENTE = NOMBRE_EMPRESA_CLIENTE;
		this.CODIGO_TIPO_CONTRATO_CLIENTE = CODIGO_TIPO_CONTRATO_CLIENTE;
		this.TIPO_CONTRATO_CLIENTE = TIPO_CONTRATO_CLIENTE;
		this.FECHA_INGRESO_EMPRESA = FECHA_INGRESO_EMPRESA;
		this.FECHA_VENCE_CONTRATO_TERMINO_FIJO = FECHA_VENCE_CONTRATO_TERMINO_FIJO;
		this.SALARIO_INTEGRAL_CLIENTE = SALARIO_INTEGRAL_CLIENTE;
		this.CARGO_ACTUAL_CLIENTE = CARGO_ACTUAL_CLIENTE;
		this.JORNADA_LABORAL_CLIENTE = JORNADA_LABORAL_CLIENTE;
		this.CODIGO_DEPENDENCIA_ACTUAL_CLIENTE = CODIGO_DEPENDENCIA_ACTUAL_CLIENTE;
		this.CODIGO_CARGO_ACTUAL_CLIENTE = CODIGO_CARGO_ACTUAL_CLIENTE;
	}

}