package com.selsa.credito.condicion_credito;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CONDICIONES_SUGERIDAS_PROSPECT implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("CODIGO_LINEA")
	@org.kie.api.definition.type.Description("Código de la línea que se está simulando en el prospecto sugerido")
	private java.lang.String CODIGO_LINEA_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Descripción de la línea que se está simulando en el prospecto sugerido")
	@org.kie.api.definition.type.Label("LINEA")
	private java.lang.String LINEA_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Código de la temporada según la línea del prospecto sugerido")
	@org.kie.api.definition.type.Label("CODIGO_TEMPORADA")
	private java.lang.String CODIGO_TEMPORADA_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Descripción de la temporada según la línea del prospecto sugerido")
	@org.kie.api.definition.type.Label("TEMPORADA")
	private java.lang.String TEMPORADA_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Código del ciclo de pago con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("CODIGO_CICLO_PAGO")
	private java.lang.String CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Descripción del ciclo de pago con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("CICLO_PAGO")
	private java.lang.String CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Código del tipo de amortización con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("CODIGO_TIPO_AMORTIZACION")
	private java.lang.String CODIGO_TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Descripción del tipo de amortización con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("TIPO_AMORTIZACION")
	private java.lang.String TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Código del medio de pago con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("CODIGO_MEDIO_PAGO")
	private java.lang.String CODIGO_MEDIO_PAGO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Medio de pago con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("MEDIO_PAGO")
	private java.lang.String MEDIO_PAGO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Código del origen de ingresos con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("CODIGO_ORIGEN_INGRESOS")
	private java.lang.String CODIGO_ORIGEN_INGRESOS_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Origen de ingresos con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("ORIGEN_INGRESOS")
	private java.lang.String ORIGEN_INGRESOS_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Código de la periodicidad de la cuota ordinaria con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("CODIGO_PERIODICIDAD_ORDINARIA")
	private java.lang.String CODIGO_PERIODICIDAD_ORDINARIA_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Fecha de la primera cuota ordinaria con la cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("FECHA_PRIMERA_CUOTA")
	private java.util.Date FECHA_PRIMERA_CUOTA_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Plazo con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("PLAZO")
	private java.lang.Integer PLAZO_SIMULAR_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Tasa nominal anual mes vencido con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("TASA_NAMV_SIMULAR")
	private Double TASA_NAMV_SIMULAR_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Monto del crédito con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("MONTO_CREDITO")
	private java.lang.Integer MONTO_CREDITO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Valor neto del crédito con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("NETO_CREDITO")
	private java.lang.Integer NETO_CREDITO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Valor de la cuota con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("VALOR_CUOTA")
	private java.lang.Integer VALOR_CUOTA_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Valor total recogido con el cual se simuló el prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("VALOR_TOTAL_RECOGIDO")
	private java.lang.Integer VALOR_TOTAL_RECOGIDO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("VALOR_TOTAL_DESCUENTOS")
	@org.kie.api.definition.type.Description("Valor total calculado de descuentos con el cual se simuló el prospecto que se sugiere al cliente")
	private java.lang.Integer VALOR_TOTAL_DESCUENTOS_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("CODIGO_DESCUENTO_CARGO")
	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Description("Código de los descuentos y/o cargos con los cuales se simuló el prospecto que se sugiere al cliente")
	private java.util.List<java.lang.String> CODIGO_DESCUENTO_CARGO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("MONTO_MAXIMO")
	@org.kie.api.definition.type.Description("Monto máximo de acuerdo a los tipos de cupo que puede solicitar en el prospecto que se sugiere al cliente")
	private java.lang.Integer MONTO_MAXIMO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("MANEJA_EXTRAORDINARIA")
	@org.kie.api.definition.type.Description("Indicador si la línea de crédito maneja cuotas extraordinarias en el prospecto que se sugiere al cliente")
	private java.lang.String MANEJA_EXTRAORDINARIA_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("VALOR_INCREMENTO")
	@org.kie.api.definition.type.Description("Valor del incremento en caso que el indicador este parametrizado asi, en el prospecto que se sugiere al cliente")
	private java.lang.Integer VALOR_INCREMENTO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("PORCENTAJE_INCREMENTO")
	@org.kie.api.definition.type.Description("Porcentaje del incremento en caso que el indicador este parametrizado asi, en el prospecto que se sugiere al cliente")
	private Double PORCENTAJE_INCREMENTO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("CAPACIDAD_PAGO_DISPONIBLE")
	@org.kie.api.definition.type.Description("Capacidad de pago disponible del prospecto que se sugiere al cliente")
	private java.lang.Integer CAPACIDAD_PAGO_DISPONIBLE_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("VALOR_DESCUBIERTO")
	@org.kie.api.definition.type.Description("Valor del descubierto del prospecto que se sugiere al cliente")
	private java.lang.Integer VALOR_DESCUBIERTO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("FACTOR_DESCUBIERTO")
	@org.kie.api.definition.type.Description("Factor del descubierto del prospecto que se sugiere al cliente")
	private Double FACTOR_DESCUBIERTO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("CALIFICACION_GARANTIA")
	@org.kie.api.definition.type.Description("Calificación de las garantías que el cliente presentó en el prospecto")
	private java.lang.String CALIFICACION_GARANTIA_PROSPECTO_SUGERIDO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Description("Número de veces del apalancamiento por línea")
	@org.kie.api.definition.type.Label("NUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO")
	private java.lang.Integer NUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("TIPO_AMORTIZACION_PROBABLE")
	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Description("Lista de tipos de amortización con los cuales el cliente puede simular en el prospecto")
	private java.util.List<java.lang.String> TIPO_AMORTIZACION_PROBABLE_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("CODIGO_MANEJA_INCREMENTOS")
	@org.kie.api.definition.type.Description("Indicador si la línea de crédito maneja incrementos en el prospecto que se sugiere al cliente")
	private java.lang.String CODIGO_MANEJA_INCREMENTOS_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("CODIGO_OPORTUNIDAD_PAGO")
	@org.kie.api.definition.type.Description("Oportunidad de pago del interés. Este valor  (Anticipado o Vencido).")
	private java.lang.String CODIGO_OPORTUNIDAD_PAGO_INTERES_CREDITO;

	@org.kie.api.definition.type.Label("PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO")
	@org.kie.api.definition.type.Description("Periodicidad de pago del interés")
	private java.lang.String CODIGO_PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO;

	@org.kie.api.definition.type.Label("CODIGO_TIPO_TASA_CREDITO")
	@org.kie.api.definition.type.Description("Tipo de tasa del crédito")
	private java.lang.String CODIGO_TIPO_TASA_CREDITO;

	@org.kie.api.definition.type.Label("CODIGO_FACTOR_VARIACION_TASA")
	private java.lang.String CODIGO_FACTOR_VARIACION_TASA;

	@org.kie.api.definition.type.Label("CODIGO_PERIODICIDAD_INCREMENTO_PROBABLE")
	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<java.lang.Integer> CODIGO_PERIODICIDAD_INCREMENTO_PROBABLE_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("CODIGO_INTERESES_AJUSTE_CICLO")
	private java.lang.String CODIGO_INTERESES_AJUSTE_CICLO;

	@org.kie.api.definition.type.Label("CODIGO_LINEA_CREDITO_RECOGER")
	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<java.lang.String> CODIGO_LINEA_CREDITO_RECOGER;

	@org.kie.api.definition.type.Label("PLAZO_MINIMO_PROBABLE")
	private java.lang.Integer PLAZO_MINIMO_PROBABLE_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("PLAZO_MAXIMO_PROBABLE")
	private java.lang.Integer PLAZO_MAXIMO_PROBABLE_PROSPECTO_SUGERIDO;

	@org.kie.api.definition.type.Label("CODIGO_OTROS_CONCEPTOS_CUOTA")
	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<java.lang.String> CODIGO_OTROS_CONCEPTOS_CUOTA;

	@org.kie.api.definition.type.Label("CODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO")
	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Description("Listas de los tipos de cupos para hallar el monto máximo que se aplicaron al monto del prospecto que se sugiere al cliente")
	private java.util.List<java.lang.String> CODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO;

	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label("TASA_NAMV_PROBABLE")
	private java.util.List<java.lang.Double> TASA_NAMV_PROBABLE_PROSPECTO_SUGERIDO;

	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label(value = "CODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA")
	private java.util.List<java.lang.String> CODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA_PROSPECTO;

	public CONDICIONES_SUGERIDAS_PROSPECT() {
	}

	public java.lang.String getCODIGO_LINEA_PROSPECTO_SUGERIDO() {
		return this.CODIGO_LINEA_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_LINEA_PROSPECTO_SUGERIDO(
			java.lang.String CODIGO_LINEA_PROSPECTO_SUGERIDO) {
		this.CODIGO_LINEA_PROSPECTO_SUGERIDO = CODIGO_LINEA_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getLINEA_PROSPECTO_SUGERIDO() {
		return this.LINEA_PROSPECTO_SUGERIDO;
	}

	public void setLINEA_PROSPECTO_SUGERIDO(
			java.lang.String LINEA_PROSPECTO_SUGERIDO) {
		this.LINEA_PROSPECTO_SUGERIDO = LINEA_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_TEMPORADA_PROSPECTO_SUGERIDO() {
		return this.CODIGO_TEMPORADA_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_TEMPORADA_PROSPECTO_SUGERIDO(
			java.lang.String CODIGO_TEMPORADA_PROSPECTO_SUGERIDO) {
		this.CODIGO_TEMPORADA_PROSPECTO_SUGERIDO = CODIGO_TEMPORADA_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getTEMPORADA_PROSPECTO_SUGERIDO() {
		return this.TEMPORADA_PROSPECTO_SUGERIDO;
	}

	public void setTEMPORADA_PROSPECTO_SUGERIDO(
			java.lang.String TEMPORADA_PROSPECTO_SUGERIDO) {
		this.TEMPORADA_PROSPECTO_SUGERIDO = TEMPORADA_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO() {
		return this.CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO(
			java.lang.String CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO) {
		this.CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO = CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO() {
		return this.CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public void setCICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO(
			java.lang.String CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO) {
		this.CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO = CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO() {
		return this.CODIGO_TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO(
			java.lang.String CODIGO_TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO) {
		this.CODIGO_TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO = CODIGO_TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getTIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO() {
		return this.TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public void setTIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO(
			java.lang.String TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO) {
		this.TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO = TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_MEDIO_PAGO_PROSPECTO_SUGERIDO() {
		return this.CODIGO_MEDIO_PAGO_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_MEDIO_PAGO_PROSPECTO_SUGERIDO(
			java.lang.String CODIGO_MEDIO_PAGO_PROSPECTO_SUGERIDO) {
		this.CODIGO_MEDIO_PAGO_PROSPECTO_SUGERIDO = CODIGO_MEDIO_PAGO_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getMEDIO_PAGO_PROSPECTO_SUGERIDO() {
		return this.MEDIO_PAGO_PROSPECTO_SUGERIDO;
	}

	public void setMEDIO_PAGO_PROSPECTO_SUGERIDO(
			java.lang.String MEDIO_PAGO_PROSPECTO_SUGERIDO) {
		this.MEDIO_PAGO_PROSPECTO_SUGERIDO = MEDIO_PAGO_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_ORIGEN_INGRESOS_PROSPECTO_SUGERIDO() {
		return this.CODIGO_ORIGEN_INGRESOS_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_ORIGEN_INGRESOS_PROSPECTO_SUGERIDO(
			java.lang.String CODIGO_ORIGEN_INGRESOS_PROSPECTO_SUGERIDO) {
		this.CODIGO_ORIGEN_INGRESOS_PROSPECTO_SUGERIDO = CODIGO_ORIGEN_INGRESOS_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getORIGEN_INGRESOS_PROSPECTO_SUGERIDO() {
		return this.ORIGEN_INGRESOS_PROSPECTO_SUGERIDO;
	}

	public void setORIGEN_INGRESOS_PROSPECTO_SUGERIDO(
			java.lang.String ORIGEN_INGRESOS_PROSPECTO_SUGERIDO) {
		this.ORIGEN_INGRESOS_PROSPECTO_SUGERIDO = ORIGEN_INGRESOS_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_PERIODICIDAD_ORDINARIA_PROSPECTO_SUGERIDO() {
		return this.CODIGO_PERIODICIDAD_ORDINARIA_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_PERIODICIDAD_ORDINARIA_PROSPECTO_SUGERIDO(
			java.lang.String CODIGO_PERIODICIDAD_ORDINARIA_PROSPECTO_SUGERIDO) {
		this.CODIGO_PERIODICIDAD_ORDINARIA_PROSPECTO_SUGERIDO = CODIGO_PERIODICIDAD_ORDINARIA_PROSPECTO_SUGERIDO;
	}

	public java.util.Date getFECHA_PRIMERA_CUOTA_PROSPECTO_SUGERIDO() {
		return this.FECHA_PRIMERA_CUOTA_PROSPECTO_SUGERIDO;
	}

	public void setFECHA_PRIMERA_CUOTA_PROSPECTO_SUGERIDO(
			java.util.Date FECHA_PRIMERA_CUOTA_PROSPECTO_SUGERIDO) {
		this.FECHA_PRIMERA_CUOTA_PROSPECTO_SUGERIDO = FECHA_PRIMERA_CUOTA_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getPLAZO_SIMULAR_PROSPECTO_SUGERIDO() {
		return this.PLAZO_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public void setPLAZO_SIMULAR_PROSPECTO_SUGERIDO(
			java.lang.Integer PLAZO_SIMULAR_PROSPECTO_SUGERIDO) {
		this.PLAZO_SIMULAR_PROSPECTO_SUGERIDO = PLAZO_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getMONTO_CREDITO_PROSPECTO_SUGERIDO() {
		return this.MONTO_CREDITO_PROSPECTO_SUGERIDO;
	}

	public void setMONTO_CREDITO_PROSPECTO_SUGERIDO(
			java.lang.Integer MONTO_CREDITO_PROSPECTO_SUGERIDO) {
		this.MONTO_CREDITO_PROSPECTO_SUGERIDO = MONTO_CREDITO_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getNETO_CREDITO_PROSPECTO_SUGERIDO() {
		return this.NETO_CREDITO_PROSPECTO_SUGERIDO;
	}

	public void setNETO_CREDITO_PROSPECTO_SUGERIDO(
			java.lang.Integer NETO_CREDITO_PROSPECTO_SUGERIDO) {
		this.NETO_CREDITO_PROSPECTO_SUGERIDO = NETO_CREDITO_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getVALOR_CUOTA_PROSPECTO_SUGERIDO() {
		return this.VALOR_CUOTA_PROSPECTO_SUGERIDO;
	}

	public void setVALOR_CUOTA_PROSPECTO_SUGERIDO(
			java.lang.Integer VALOR_CUOTA_PROSPECTO_SUGERIDO) {
		this.VALOR_CUOTA_PROSPECTO_SUGERIDO = VALOR_CUOTA_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getVALOR_TOTAL_RECOGIDO_PROSPECTO_SUGERIDO() {
		return this.VALOR_TOTAL_RECOGIDO_PROSPECTO_SUGERIDO;
	}

	public void setVALOR_TOTAL_RECOGIDO_PROSPECTO_SUGERIDO(
			java.lang.Integer VALOR_TOTAL_RECOGIDO_PROSPECTO_SUGERIDO) {
		this.VALOR_TOTAL_RECOGIDO_PROSPECTO_SUGERIDO = VALOR_TOTAL_RECOGIDO_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getVALOR_TOTAL_DESCUENTOS_PROSPECTO_SUGERIDO() {
		return this.VALOR_TOTAL_DESCUENTOS_PROSPECTO_SUGERIDO;
	}

	public void setVALOR_TOTAL_DESCUENTOS_PROSPECTO_SUGERIDO(
			java.lang.Integer VALOR_TOTAL_DESCUENTOS_PROSPECTO_SUGERIDO) {
		this.VALOR_TOTAL_DESCUENTOS_PROSPECTO_SUGERIDO = VALOR_TOTAL_DESCUENTOS_PROSPECTO_SUGERIDO;
	}

	public java.util.List<java.lang.String> getCODIGO_DESCUENTO_CARGO_PROSPECTO_SUGERIDO() {
		return this.CODIGO_DESCUENTO_CARGO_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_DESCUENTO_CARGO_PROSPECTO_SUGERIDO(
			java.util.List<java.lang.String> CODIGO_DESCUENTO_CARGO_PROSPECTO_SUGERIDO) {
		this.CODIGO_DESCUENTO_CARGO_PROSPECTO_SUGERIDO = CODIGO_DESCUENTO_CARGO_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getMONTO_MAXIMO_PROSPECTO_SUGERIDO() {
		return this.MONTO_MAXIMO_PROSPECTO_SUGERIDO;
	}

	public void setMONTO_MAXIMO_PROSPECTO_SUGERIDO(
			java.lang.Integer MONTO_MAXIMO_PROSPECTO_SUGERIDO) {
		this.MONTO_MAXIMO_PROSPECTO_SUGERIDO = MONTO_MAXIMO_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getMANEJA_EXTRAORDINARIA_PROSPECTO_SUGERIDO() {
		return this.MANEJA_EXTRAORDINARIA_PROSPECTO_SUGERIDO;
	}

	public void setMANEJA_EXTRAORDINARIA_PROSPECTO_SUGERIDO(
			java.lang.String MANEJA_EXTRAORDINARIA_PROSPECTO_SUGERIDO) {
		this.MANEJA_EXTRAORDINARIA_PROSPECTO_SUGERIDO = MANEJA_EXTRAORDINARIA_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getVALOR_INCREMENTO_PROSPECTO_SUGERIDO() {
		return this.VALOR_INCREMENTO_PROSPECTO_SUGERIDO;
	}

	public void setVALOR_INCREMENTO_PROSPECTO_SUGERIDO(
			java.lang.Integer VALOR_INCREMENTO_PROSPECTO_SUGERIDO) {
		this.VALOR_INCREMENTO_PROSPECTO_SUGERIDO = VALOR_INCREMENTO_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getCAPACIDAD_PAGO_DISPONIBLE_PROSPECTO_SUGERIDO() {
		return this.CAPACIDAD_PAGO_DISPONIBLE_PROSPECTO_SUGERIDO;
	}

	public void setCAPACIDAD_PAGO_DISPONIBLE_PROSPECTO_SUGERIDO(
			java.lang.Integer CAPACIDAD_PAGO_DISPONIBLE_PROSPECTO_SUGERIDO) {
		this.CAPACIDAD_PAGO_DISPONIBLE_PROSPECTO_SUGERIDO = CAPACIDAD_PAGO_DISPONIBLE_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getVALOR_DESCUBIERTO_PROSPECTO_SUGERIDO() {
		return this.VALOR_DESCUBIERTO_PROSPECTO_SUGERIDO;
	}

	public void setVALOR_DESCUBIERTO_PROSPECTO_SUGERIDO(
			java.lang.Integer VALOR_DESCUBIERTO_PROSPECTO_SUGERIDO) {
		this.VALOR_DESCUBIERTO_PROSPECTO_SUGERIDO = VALOR_DESCUBIERTO_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCALIFICACION_GARANTIA_PROSPECTO_SUGERIDO_PROSPECTO_SUGERIDO() {
		return this.CALIFICACION_GARANTIA_PROSPECTO_SUGERIDO_PROSPECTO_SUGERIDO;
	}

	public void setCALIFICACION_GARANTIA_PROSPECTO_SUGERIDO_PROSPECTO_SUGERIDO(
			java.lang.String CALIFICACION_GARANTIA_PROSPECTO_SUGERIDO_PROSPECTO_SUGERIDO) {
		this.CALIFICACION_GARANTIA_PROSPECTO_SUGERIDO_PROSPECTO_SUGERIDO = CALIFICACION_GARANTIA_PROSPECTO_SUGERIDO_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getNUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO() {
		return this.NUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO;
	}

	public void setNUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO(
			java.lang.Integer NUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO) {
		this.NUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO = NUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO;
	}

	public java.util.List<java.lang.String> getTIPO_AMORTIZACION_PROBABLE_PROSPECTO_SUGERIDO() {
		return this.TIPO_AMORTIZACION_PROBABLE_PROSPECTO_SUGERIDO;
	}

	public void setTIPO_AMORTIZACION_PROBABLE_PROSPECTO_SUGERIDO(
			java.util.List<java.lang.String> TIPO_AMORTIZACION_PROBABLE_PROSPECTO_SUGERIDO) {
		this.TIPO_AMORTIZACION_PROBABLE_PROSPECTO_SUGERIDO = TIPO_AMORTIZACION_PROBABLE_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_MANEJA_INCREMENTOS_PROSPECTO_SUGERIDO() {
		return this.CODIGO_MANEJA_INCREMENTOS_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_MANEJA_INCREMENTOS_PROSPECTO_SUGERIDO(
			java.lang.String CODIGO_MANEJA_INCREMENTOS_PROSPECTO_SUGERIDO) {
		this.CODIGO_MANEJA_INCREMENTOS_PROSPECTO_SUGERIDO = CODIGO_MANEJA_INCREMENTOS_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_OPORTUNIDAD_PAGO_INTERES_CREDITO() {
		return this.CODIGO_OPORTUNIDAD_PAGO_INTERES_CREDITO;
	}

	public void setCODIGO_OPORTUNIDAD_PAGO_INTERES_CREDITO(
			java.lang.String CODIGO_OPORTUNIDAD_PAGO_INTERES_CREDITO) {
		this.CODIGO_OPORTUNIDAD_PAGO_INTERES_CREDITO = CODIGO_OPORTUNIDAD_PAGO_INTERES_CREDITO;
	}

	public java.lang.String getCODIGO_PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO() {
		return this.CODIGO_PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO;
	}

	public void setCODIGO_PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO(
			java.lang.String CODIGO_PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO) {
		this.CODIGO_PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO = CODIGO_PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO;
	}

	public java.lang.String getCODIGO_TIPO_TASA_CREDITO() {
		return this.CODIGO_TIPO_TASA_CREDITO;
	}

	public void setCODIGO_TIPO_TASA_CREDITO(
			java.lang.String CODIGO_TIPO_TASA_CREDITO) {
		this.CODIGO_TIPO_TASA_CREDITO = CODIGO_TIPO_TASA_CREDITO;
	}

	public java.lang.String getCODIGO_FACTOR_VARIACION_TASA() {
		return this.CODIGO_FACTOR_VARIACION_TASA;
	}

	public void setCODIGO_FACTOR_VARIACION_TASA(
			java.lang.String CODIGO_FACTOR_VARIACION_TASA) {
		this.CODIGO_FACTOR_VARIACION_TASA = CODIGO_FACTOR_VARIACION_TASA;
	}

	public java.util.List<java.lang.Integer> getCODIGO_PERIODICIDAD_INCREMENTO_PROBABLE_PROSPECTO_SUGERIDO() {
		return this.CODIGO_PERIODICIDAD_INCREMENTO_PROBABLE_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_PERIODICIDAD_INCREMENTO_PROBABLE_PROSPECTO_SUGERIDO(
			java.util.List<java.lang.Integer> CODIGO_PERIODICIDAD_INCREMENTO_PROBABLE_PROSPECTO_SUGERIDO) {
		this.CODIGO_PERIODICIDAD_INCREMENTO_PROBABLE_PROSPECTO_SUGERIDO = CODIGO_PERIODICIDAD_INCREMENTO_PROBABLE_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_INTERESES_AJUSTE_CICLO() {
		return this.CODIGO_INTERESES_AJUSTE_CICLO;
	}

	public void setCODIGO_INTERESES_AJUSTE_CICLO(
			java.lang.String CODIGO_INTERESES_AJUSTE_CICLO) {
		this.CODIGO_INTERESES_AJUSTE_CICLO = CODIGO_INTERESES_AJUSTE_CICLO;
	}

	public java.util.List<java.lang.String> getCODIGO_LINEA_CREDITO_RECOGER() {
		return this.CODIGO_LINEA_CREDITO_RECOGER;
	}

	public void setCODIGO_LINEA_CREDITO_RECOGER(
			java.util.List<java.lang.String> CODIGO_LINEA_CREDITO_RECOGER) {
		this.CODIGO_LINEA_CREDITO_RECOGER = CODIGO_LINEA_CREDITO_RECOGER;
	}

	public java.lang.Integer getPLAZO_MINIMO_PROBABLE_PROSPECTO_SUGERIDO() {
		return this.PLAZO_MINIMO_PROBABLE_PROSPECTO_SUGERIDO;
	}

	public void setPLAZO_MINIMO_PROBABLE_PROSPECTO_SUGERIDO(
			java.lang.Integer PLAZO_MINIMO_PROBABLE_PROSPECTO_SUGERIDO) {
		this.PLAZO_MINIMO_PROBABLE_PROSPECTO_SUGERIDO = PLAZO_MINIMO_PROBABLE_PROSPECTO_SUGERIDO;
	}

	public java.lang.Integer getPLAZO_MAXIMO_PROBABLE_PROSPECTO_SUGERIDO() {
		return this.PLAZO_MAXIMO_PROBABLE_PROSPECTO_SUGERIDO;
	}

	public void setPLAZO_MAXIMO_PROBABLE_PROSPECTO_SUGERIDO(
			java.lang.Integer PLAZO_MAXIMO_PROBABLE_PROSPECTO_SUGERIDO) {
		this.PLAZO_MAXIMO_PROBABLE_PROSPECTO_SUGERIDO = PLAZO_MAXIMO_PROBABLE_PROSPECTO_SUGERIDO;
	}

	public java.util.List<java.lang.String> getCODIGO_OTROS_CONCEPTOS_CUOTA() {
		return this.CODIGO_OTROS_CONCEPTOS_CUOTA;
	}

	public void setCODIGO_OTROS_CONCEPTOS_CUOTA(
			java.util.List<java.lang.String> CODIGO_OTROS_CONCEPTOS_CUOTA) {
		this.CODIGO_OTROS_CONCEPTOS_CUOTA = CODIGO_OTROS_CONCEPTOS_CUOTA;
	}

	public java.util.List<java.lang.String> getCODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO() {
		return this.CODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO(
			java.util.List<java.lang.String> CODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO) {
		this.CODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO = CODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO;
	}

	public java.lang.Double getTASA_NAMV_SIMULAR_PROSPECTO_SUGERIDO() {
		return this.TASA_NAMV_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public void setTASA_NAMV_SIMULAR_PROSPECTO_SUGERIDO(
			java.lang.Double TASA_NAMV_SIMULAR_PROSPECTO_SUGERIDO) {
		this.TASA_NAMV_SIMULAR_PROSPECTO_SUGERIDO = TASA_NAMV_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public java.lang.Double getPORCENTAJE_INCREMENTO_PROSPECTO_SUGERIDO() {
		return this.PORCENTAJE_INCREMENTO_PROSPECTO_SUGERIDO;
	}

	public void setPORCENTAJE_INCREMENTO_PROSPECTO_SUGERIDO(
			java.lang.Double PORCENTAJE_INCREMENTO_PROSPECTO_SUGERIDO) {
		this.PORCENTAJE_INCREMENTO_PROSPECTO_SUGERIDO = PORCENTAJE_INCREMENTO_PROSPECTO_SUGERIDO;
	}

	public java.lang.Double getFACTOR_DESCUBIERTO_PROSPECTO_SUGERIDO() {
		return this.FACTOR_DESCUBIERTO_PROSPECTO_SUGERIDO;
	}

	public void setFACTOR_DESCUBIERTO_PROSPECTO_SUGERIDO(
			java.lang.Double FACTOR_DESCUBIERTO_PROSPECTO_SUGERIDO) {
		this.FACTOR_DESCUBIERTO_PROSPECTO_SUGERIDO = FACTOR_DESCUBIERTO_PROSPECTO_SUGERIDO;
	}

	public java.util.List<java.lang.Double> getTASA_NAMV_PROBABLE_PROSPECTO_SUGERIDO() {
		return this.TASA_NAMV_PROBABLE_PROSPECTO_SUGERIDO;
	}

	public void setTASA_NAMV_PROBABLE_PROSPECTO_SUGERIDO(
			java.util.List<java.lang.Double> TASA_NAMV_PROBABLE_PROSPECTO_SUGERIDO) {
		this.TASA_NAMV_PROBABLE_PROSPECTO_SUGERIDO = TASA_NAMV_PROBABLE_PROSPECTO_SUGERIDO;
	}

	public java.util.List<java.lang.String> getCODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA_PROSPECTO() {
		return this.CODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA_PROSPECTO;
	}

	public void setCODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA_PROSPECTO(
			java.util.List<java.lang.String> CODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA_PROSPECTO) {
		this.CODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA_PROSPECTO = CODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA_PROSPECTO;
	}

	public CONDICIONES_SUGERIDAS_PROSPECT(
			java.lang.String CODIGO_LINEA_PROSPECTO_SUGERIDO,
			java.lang.String LINEA_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_TEMPORADA_PROSPECTO_SUGERIDO,
			java.lang.String TEMPORADA_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO,
			java.lang.String CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO,
			java.lang.String TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_MEDIO_PAGO_PROSPECTO_SUGERIDO,
			java.lang.String MEDIO_PAGO_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_ORIGEN_INGRESOS_PROSPECTO_SUGERIDO,
			java.lang.String ORIGEN_INGRESOS_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_PERIODICIDAD_ORDINARIA_PROSPECTO_SUGERIDO,
			java.util.Date FECHA_PRIMERA_CUOTA_PROSPECTO_SUGERIDO,
			java.lang.Integer PLAZO_SIMULAR_PROSPECTO_SUGERIDO,
			java.lang.Double TASA_NAMV_SIMULAR_PROSPECTO_SUGERIDO,
			java.lang.Integer MONTO_CREDITO_PROSPECTO_SUGERIDO,
			java.lang.Integer NETO_CREDITO_PROSPECTO_SUGERIDO,
			java.lang.Integer VALOR_CUOTA_PROSPECTO_SUGERIDO,
			java.lang.Integer VALOR_TOTAL_RECOGIDO_PROSPECTO_SUGERIDO,
			java.lang.Integer VALOR_TOTAL_DESCUENTOS_PROSPECTO_SUGERIDO,
			java.util.List<java.lang.String> CODIGO_DESCUENTO_CARGO_PROSPECTO_SUGERIDO,
			java.lang.Integer MONTO_MAXIMO_PROSPECTO_SUGERIDO,
			java.lang.String MANEJA_EXTRAORDINARIA_PROSPECTO_SUGERIDO,
			java.lang.Integer VALOR_INCREMENTO_PROSPECTO_SUGERIDO,
			java.lang.Double PORCENTAJE_INCREMENTO_PROSPECTO_SUGERIDO,
			java.lang.Integer CAPACIDAD_PAGO_DISPONIBLE_PROSPECTO_SUGERIDO,
			java.lang.Integer VALOR_DESCUBIERTO_PROSPECTO_SUGERIDO,
			java.lang.Double FACTOR_DESCUBIERTO_PROSPECTO_SUGERIDO,
			java.lang.String CALIFICACION_GARANTIA_PROSPECTO_SUGERIDO_PROSPECTO_SUGERIDO,
			java.lang.Integer NUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO,
			java.util.List<java.lang.String> TIPO_AMORTIZACION_PROBABLE_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_MANEJA_INCREMENTOS_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_OPORTUNIDAD_PAGO_INTERES_CREDITO,
			java.lang.String CODIGO_PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO,
			java.lang.String CODIGO_TIPO_TASA_CREDITO,
			java.lang.String CODIGO_FACTOR_VARIACION_TASA,
			java.util.List<java.lang.Integer> CODIGO_PERIODICIDAD_INCREMENTO_PROBABLE_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_INTERESES_AJUSTE_CICLO,
			java.util.List<java.lang.String> CODIGO_LINEA_CREDITO_RECOGER,
			java.lang.Integer PLAZO_MINIMO_PROBABLE_PROSPECTO_SUGERIDO,
			java.lang.Integer PLAZO_MAXIMO_PROBABLE_PROSPECTO_SUGERIDO,
			java.util.List<java.lang.String> CODIGO_OTROS_CONCEPTOS_CUOTA,
			java.util.List<java.lang.String> CODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO,
			java.util.List<java.lang.Double> TASA_NAMV_PROBABLE_PROSPECTO_SUGERIDO,
			java.util.List<java.lang.String> CODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA_PROSPECTO) {
		this.CODIGO_LINEA_PROSPECTO_SUGERIDO = CODIGO_LINEA_PROSPECTO_SUGERIDO;
		this.LINEA_PROSPECTO_SUGERIDO = LINEA_PROSPECTO_SUGERIDO;
		this.CODIGO_TEMPORADA_PROSPECTO_SUGERIDO = CODIGO_TEMPORADA_PROSPECTO_SUGERIDO;
		this.TEMPORADA_PROSPECTO_SUGERIDO = TEMPORADA_PROSPECTO_SUGERIDO;
		this.CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO = CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;
		this.CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO = CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;
		this.CODIGO_TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO = CODIGO_TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO;
		this.TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO = TIPO_AMORTIZACION_SIMULAR_PROSPECTO_SUGERIDO;
		this.CODIGO_MEDIO_PAGO_PROSPECTO_SUGERIDO = CODIGO_MEDIO_PAGO_PROSPECTO_SUGERIDO;
		this.MEDIO_PAGO_PROSPECTO_SUGERIDO = MEDIO_PAGO_PROSPECTO_SUGERIDO;
		this.CODIGO_ORIGEN_INGRESOS_PROSPECTO_SUGERIDO = CODIGO_ORIGEN_INGRESOS_PROSPECTO_SUGERIDO;
		this.ORIGEN_INGRESOS_PROSPECTO_SUGERIDO = ORIGEN_INGRESOS_PROSPECTO_SUGERIDO;
		this.CODIGO_PERIODICIDAD_ORDINARIA_PROSPECTO_SUGERIDO = CODIGO_PERIODICIDAD_ORDINARIA_PROSPECTO_SUGERIDO;
		this.FECHA_PRIMERA_CUOTA_PROSPECTO_SUGERIDO = FECHA_PRIMERA_CUOTA_PROSPECTO_SUGERIDO;
		this.PLAZO_SIMULAR_PROSPECTO_SUGERIDO = PLAZO_SIMULAR_PROSPECTO_SUGERIDO;
		this.TASA_NAMV_SIMULAR_PROSPECTO_SUGERIDO = TASA_NAMV_SIMULAR_PROSPECTO_SUGERIDO;
		this.MONTO_CREDITO_PROSPECTO_SUGERIDO = MONTO_CREDITO_PROSPECTO_SUGERIDO;
		this.NETO_CREDITO_PROSPECTO_SUGERIDO = NETO_CREDITO_PROSPECTO_SUGERIDO;
		this.VALOR_CUOTA_PROSPECTO_SUGERIDO = VALOR_CUOTA_PROSPECTO_SUGERIDO;
		this.VALOR_TOTAL_RECOGIDO_PROSPECTO_SUGERIDO = VALOR_TOTAL_RECOGIDO_PROSPECTO_SUGERIDO;
		this.VALOR_TOTAL_DESCUENTOS_PROSPECTO_SUGERIDO = VALOR_TOTAL_DESCUENTOS_PROSPECTO_SUGERIDO;
		this.CODIGO_DESCUENTO_CARGO_PROSPECTO_SUGERIDO = CODIGO_DESCUENTO_CARGO_PROSPECTO_SUGERIDO;
		this.MONTO_MAXIMO_PROSPECTO_SUGERIDO = MONTO_MAXIMO_PROSPECTO_SUGERIDO;
		this.MANEJA_EXTRAORDINARIA_PROSPECTO_SUGERIDO = MANEJA_EXTRAORDINARIA_PROSPECTO_SUGERIDO;
		this.VALOR_INCREMENTO_PROSPECTO_SUGERIDO = VALOR_INCREMENTO_PROSPECTO_SUGERIDO;
		this.PORCENTAJE_INCREMENTO_PROSPECTO_SUGERIDO = PORCENTAJE_INCREMENTO_PROSPECTO_SUGERIDO;
		this.CAPACIDAD_PAGO_DISPONIBLE_PROSPECTO_SUGERIDO = CAPACIDAD_PAGO_DISPONIBLE_PROSPECTO_SUGERIDO;
		this.VALOR_DESCUBIERTO_PROSPECTO_SUGERIDO = VALOR_DESCUBIERTO_PROSPECTO_SUGERIDO;
		this.FACTOR_DESCUBIERTO_PROSPECTO_SUGERIDO = FACTOR_DESCUBIERTO_PROSPECTO_SUGERIDO;
		this.CALIFICACION_GARANTIA_PROSPECTO_SUGERIDO_PROSPECTO_SUGERIDO = CALIFICACION_GARANTIA_PROSPECTO_SUGERIDO_PROSPECTO_SUGERIDO;
		this.NUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO = NUMERO_VECES_APALANCAMIENTO_PROSPECTO_SUGERIDO;
		this.TIPO_AMORTIZACION_PROBABLE_PROSPECTO_SUGERIDO = TIPO_AMORTIZACION_PROBABLE_PROSPECTO_SUGERIDO;
		this.CODIGO_MANEJA_INCREMENTOS_PROSPECTO_SUGERIDO = CODIGO_MANEJA_INCREMENTOS_PROSPECTO_SUGERIDO;
		this.CODIGO_OPORTUNIDAD_PAGO_INTERES_CREDITO = CODIGO_OPORTUNIDAD_PAGO_INTERES_CREDITO;
		this.CODIGO_PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO = CODIGO_PERIODICIDAD_INTERES_ABONO_FIJO_CREDITO;
		this.CODIGO_TIPO_TASA_CREDITO = CODIGO_TIPO_TASA_CREDITO;
		this.CODIGO_FACTOR_VARIACION_TASA = CODIGO_FACTOR_VARIACION_TASA;
		this.CODIGO_PERIODICIDAD_INCREMENTO_PROBABLE_PROSPECTO_SUGERIDO = CODIGO_PERIODICIDAD_INCREMENTO_PROBABLE_PROSPECTO_SUGERIDO;
		this.CODIGO_INTERESES_AJUSTE_CICLO = CODIGO_INTERESES_AJUSTE_CICLO;
		this.CODIGO_LINEA_CREDITO_RECOGER = CODIGO_LINEA_CREDITO_RECOGER;
		this.PLAZO_MINIMO_PROBABLE_PROSPECTO_SUGERIDO = PLAZO_MINIMO_PROBABLE_PROSPECTO_SUGERIDO;
		this.PLAZO_MAXIMO_PROBABLE_PROSPECTO_SUGERIDO = PLAZO_MAXIMO_PROBABLE_PROSPECTO_SUGERIDO;
		this.CODIGO_OTROS_CONCEPTOS_CUOTA = CODIGO_OTROS_CONCEPTOS_CUOTA;
		this.CODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO = CODIGO_TIPO_CUPO_PROSPECTO_SUGERIDO;
		this.TASA_NAMV_PROBABLE_PROSPECTO_SUGERIDO = TASA_NAMV_PROBABLE_PROSPECTO_SUGERIDO;
		this.CODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA_PROSPECTO = CODIGO_ORIGEN_INGRESOS_EXTRAORDINARIA_PROSPECTO;
	}

}