package com.selsa.credito.condicion_credito;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CONDICION_FECHA_CUOTA_CREDITO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "CODIGO_LINEA")
	private java.lang.String CODIGO_LINEA_PROSPECTO_SUGERIDO;
	@org.kie.api.definition.type.Label(value = "CODIGO_CICLO_PAGO")
	private java.lang.String CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;
	@org.kie.api.definition.type.Label(value = "CODIGO_VENCIMIENTO_VARIABLE")
	private java.lang.String CODIGO_VENCIMIENTO_VARIABLE;
	@org.kie.api.definition.type.Label(value = "DIA_VENCIMIENTO_FIJO")
	private java.lang.Integer DIA_VENCIMIENTO_FIJO;
	@org.kie.api.definition.type.Label(value = "DIAS_ATRAS_CORTE_NOVEDADES ")
	private java.lang.Integer DIAS_ATRAS_CORTE_NOVEDADES;
	@org.kie.api.definition.type.Label(value = "DIA_VENCIMIENTO_EXTR")
	private java.lang.Integer DIA_VENCIMIENTO_EXTR;
	@org.kie.api.definition.type.Label(value = "MES_VENCIMIENTO_EXT")
	private java.lang.Integer MES_VENCIMIENTO_EXT;
	@org.kie.api.definition.type.Label(value = "DIAS_CORTE_NOVEDADES")
	private java.lang.Integer DIAS_CORTE_NOVEDADES;

	public CONDICION_FECHA_CUOTA_CREDITO() {
	}

	public java.lang.String getCODIGO_LINEA_PROSPECTO_SUGERIDO() {
		return this.CODIGO_LINEA_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_LINEA_PROSPECTO_SUGERIDO(
			java.lang.String CODIGO_LINEA_PROSPECTO_SUGERIDO) {
		this.CODIGO_LINEA_PROSPECTO_SUGERIDO = CODIGO_LINEA_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO() {
		return this.CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public void setCODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO(
			java.lang.String CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO) {
		this.CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO = CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;
	}

	public java.lang.String getCODIGO_VENCIMIENTO_VARIABLE() {
		return this.CODIGO_VENCIMIENTO_VARIABLE;
	}

	public void setCODIGO_VENCIMIENTO_VARIABLE(
			java.lang.String CODIGO_VENCIMIENTO_VARIABLE) {
		this.CODIGO_VENCIMIENTO_VARIABLE = CODIGO_VENCIMIENTO_VARIABLE;
	}

	public java.lang.Integer getDIA_VENCIMIENTO_FIJO() {
		return this.DIA_VENCIMIENTO_FIJO;
	}

	public void setDIA_VENCIMIENTO_FIJO(java.lang.Integer DIA_VENCIMIENTO_FIJO) {
		this.DIA_VENCIMIENTO_FIJO = DIA_VENCIMIENTO_FIJO;
	}

	public java.lang.Integer getDIAS_ATRAS_CORTE_NOVEDADES() {
		return this.DIAS_ATRAS_CORTE_NOVEDADES;
	}

	public void setDIAS_ATRAS_CORTE_NOVEDADES(
			java.lang.Integer DIAS_ATRAS_CORTE_NOVEDADES) {
		this.DIAS_ATRAS_CORTE_NOVEDADES = DIAS_ATRAS_CORTE_NOVEDADES;
	}

	public java.lang.Integer getDIA_VENCIMIENTO_EXTR() {
		return this.DIA_VENCIMIENTO_EXTR;
	}

	public void setDIA_VENCIMIENTO_EXTR(java.lang.Integer DIA_VENCIMIENTO_EXTR) {
		this.DIA_VENCIMIENTO_EXTR = DIA_VENCIMIENTO_EXTR;
	}

	public java.lang.Integer getMES_VENCIMIENTO_EXT() {
		return this.MES_VENCIMIENTO_EXT;
	}

	public void setMES_VENCIMIENTO_EXT(java.lang.Integer MES_VENCIMIENTO_EXT) {
		this.MES_VENCIMIENTO_EXT = MES_VENCIMIENTO_EXT;
	}

	public java.lang.Integer getDIAS_CORTE_NOVEDADES() {
		return this.DIAS_CORTE_NOVEDADES;
	}

	public void setDIAS_CORTE_NOVEDADES(java.lang.Integer DIAS_CORTE_NOVEDADES) {
		this.DIAS_CORTE_NOVEDADES = DIAS_CORTE_NOVEDADES;
	}

	public CONDICION_FECHA_CUOTA_CREDITO(
			java.lang.String CODIGO_LINEA_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO,
			java.lang.String CODIGO_VENCIMIENTO_VARIABLE,
			java.lang.Integer DIA_VENCIMIENTO_FIJO,
			java.lang.Integer DIAS_ATRAS_CORTE_NOVEDADES,
			java.lang.Integer DIA_VENCIMIENTO_EXTR,
			java.lang.Integer MES_VENCIMIENTO_EXT,
			java.lang.Integer DIAS_CORTE_NOVEDADES) {
		this.CODIGO_LINEA_PROSPECTO_SUGERIDO = CODIGO_LINEA_PROSPECTO_SUGERIDO;
		this.CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO = CODIGO_CICLO_PAGO_SIMULAR_PROSPECTO_SUGERIDO;
		this.CODIGO_VENCIMIENTO_VARIABLE = CODIGO_VENCIMIENTO_VARIABLE;
		this.DIA_VENCIMIENTO_FIJO = DIA_VENCIMIENTO_FIJO;
		this.DIAS_ATRAS_CORTE_NOVEDADES = DIAS_ATRAS_CORTE_NOVEDADES;
		this.DIA_VENCIMIENTO_EXTR = DIA_VENCIMIENTO_EXTR;
		this.MES_VENCIMIENTO_EXT = MES_VENCIMIENTO_EXT;
		this.DIAS_CORTE_NOVEDADES = DIAS_CORTE_NOVEDADES;
	}

}