package com.selsa.credito.condicion_credito;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PROSPECTO_OTRO_CONCEPTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Description("Código de los otros conceptos que se calcularon y afectan el valor de la cuota ordinaria del prospecto que se sugiere al cliente")
	@org.kie.api.definition.type.Label("CODIGO_OTRO_CONCEPTO")
	private java.lang.String CODIGO_OTRO_CONCEPTO;
	@org.kie.api.definition.type.Label("BASE_CALCULO_OTRO_CONCEPTO")
	private java.lang.String BASE_CALCULO_OTRO_CONCEPTO;
	@org.kie.api.definition.type.Label("PORCENTAJE_OTRO_CONCEPTO")
	private Double PORCENTAJE_OTRO_CONCEPTO;
	@org.kie.api.definition.type.Label("CODIGO_TIPO_CALCULO_OTRO_CONCEPTO")
	private java.lang.String CODIGO_TIPO_CALCULO_OTRO_CONCEPTO;
	@org.kie.api.definition.type.Label("VALOR_CALCULADO_OTRO_CONCEPTO")
	private java.lang.Integer VALOR_CALCULADO_OTRO_CONCEPTO;

	@org.kie.api.definition.type.Label(value = "VALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO")
	private java.lang.Integer VALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO;

	public PROSPECTO_OTRO_CONCEPTO() {
	}

	public java.lang.String getCODIGO_OTRO_CONCEPTO() {
		return this.CODIGO_OTRO_CONCEPTO;
	}

	public void setCODIGO_OTRO_CONCEPTO(java.lang.String CODIGO_OTRO_CONCEPTO) {
		this.CODIGO_OTRO_CONCEPTO = CODIGO_OTRO_CONCEPTO;
	}

	public java.lang.String getBASE_CALCULO_OTRO_CONCEPTO() {
		return this.BASE_CALCULO_OTRO_CONCEPTO;
	}

	public void setBASE_CALCULO_OTRO_CONCEPTO(
			java.lang.String BASE_CALCULO_OTRO_CONCEPTO) {
		this.BASE_CALCULO_OTRO_CONCEPTO = BASE_CALCULO_OTRO_CONCEPTO;
	}

	public java.lang.String getCODIGO_TIPO_CALCULO_OTRO_CONCEPTO() {
		return this.CODIGO_TIPO_CALCULO_OTRO_CONCEPTO;
	}

	public void setCODIGO_TIPO_CALCULO_OTRO_CONCEPTO(
			java.lang.String CODIGO_TIPO_CALCULO_OTRO_CONCEPTO) {
		this.CODIGO_TIPO_CALCULO_OTRO_CONCEPTO = CODIGO_TIPO_CALCULO_OTRO_CONCEPTO;
	}

	public java.lang.Integer getVALOR_CALCULADO_OTRO_CONCEPTO() {
		return this.VALOR_CALCULADO_OTRO_CONCEPTO;
	}

	public void setVALOR_CALCULADO_OTRO_CONCEPTO(
			java.lang.Integer VALOR_CALCULADO_OTRO_CONCEPTO) {
		this.VALOR_CALCULADO_OTRO_CONCEPTO = VALOR_CALCULADO_OTRO_CONCEPTO;
	}

	public java.lang.Double getPORCENTAJE_OTRO_CONCEPTO() {
		return this.PORCENTAJE_OTRO_CONCEPTO;
	}

	public void setPORCENTAJE_OTRO_CONCEPTO(
			java.lang.Double PORCENTAJE_OTRO_CONCEPTO) {
		this.PORCENTAJE_OTRO_CONCEPTO = PORCENTAJE_OTRO_CONCEPTO;
	}

	public java.lang.Integer getVALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO() {
		return this.VALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO;
	}

	public void setVALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO(
			java.lang.Integer VALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO) {
		this.VALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO = VALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO;
	}

	public PROSPECTO_OTRO_CONCEPTO(java.lang.String CODIGO_OTRO_CONCEPTO,
			java.lang.String BASE_CALCULO_OTRO_CONCEPTO,
			java.lang.Double PORCENTAJE_OTRO_CONCEPTO,
			java.lang.String CODIGO_TIPO_CALCULO_OTRO_CONCEPTO,
			java.lang.Integer VALOR_CALCULADO_OTRO_CONCEPTO,
			java.lang.Integer VALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO) {
		this.CODIGO_OTRO_CONCEPTO = CODIGO_OTRO_CONCEPTO;
		this.BASE_CALCULO_OTRO_CONCEPTO = BASE_CALCULO_OTRO_CONCEPTO;
		this.PORCENTAJE_OTRO_CONCEPTO = PORCENTAJE_OTRO_CONCEPTO;
		this.CODIGO_TIPO_CALCULO_OTRO_CONCEPTO = CODIGO_TIPO_CALCULO_OTRO_CONCEPTO;
		this.VALOR_CALCULADO_OTRO_CONCEPTO = VALOR_CALCULADO_OTRO_CONCEPTO;
		this.VALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO = VALOR_ABSOLUTO_TOTAL_OTRO_CONCEPTO;
	}

}