package com.selsa.credito.condicion_credito;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class VARIABLES_ANALISIS_LINEAS implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("CODIGO_LINEA_ANALISIS")
	@org.kie.api.definition.type.Description("Código de la línea par la cual se van a hacer los análisis")
	private java.lang.String CODIGO_LINEA_ANALISIS;

	public VARIABLES_ANALISIS_LINEAS() {
	}

	public java.lang.String getCODIGO_LINEA_ANALISIS() {
		return this.CODIGO_LINEA_ANALISIS;
	}

	public void setCODIGO_LINEA_ANALISIS(java.lang.String CODIGO_LINEA_ANALISIS) {
		this.CODIGO_LINEA_ANALISIS = CODIGO_LINEA_ANALISIS;
	}

	public VARIABLES_ANALISIS_LINEAS(java.lang.String CODIGO_LINEA_ANALISIS) {
		this.CODIGO_LINEA_ANALISIS = CODIGO_LINEA_ANALISIS;
	}

}